/* GENERATED by scripts/build-schema.mjs. Edit db/*.sql, not this file. */

export const SCHEMA_SQL = `-- ===========================================================================
-- Bright Future Secondary School - portal schema
-- Apply with:  psql "$DATABASE_URL" -f db/schema.sql
-- Safe to re-run.
-- ===========================================================================

-- --- The register: who is actually enrolled -------------------------------
-- Source of truth, imported from the school's spreadsheet. Nobody can create
-- an account unless they match a row here.
CREATE TABLE IF NOT EXISTS register (
  id             BIGSERIAL PRIMARY KEY,
  admission_no   TEXT        NOT NULL,
  surname        TEXT        NOT NULL,
  other_names    TEXT        NOT NULL DEFAULT '',
  class_level    TEXT        NOT NULL,
  guardian_email TEXT,
  guardian_phone TEXT,
  status         TEXT        NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active', 'left')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Admission numbers are matched case- and space-insensitively.
CREATE UNIQUE INDEX IF NOT EXISTS register_admission_no_key
  ON register (upper(replace(admission_no, ' ', '')));

-- --- Staff register: teacher accounts are checked against this ------------
CREATE TABLE IF NOT EXISTS staff_register (
  id          BIGSERIAL PRIMARY KEY,
  staff_no    TEXT        NOT NULL,
  surname     TEXT        NOT NULL,
  other_names TEXT        NOT NULL DEFAULT '',
  email       TEXT,
  status      TEXT        NOT NULL DEFAULT 'active'
              CHECK (status IN ('active', 'left')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS staff_register_staff_no_key
  ON staff_register (upper(replace(staff_no, ' ', '')));

-- --- Accounts -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            BIGSERIAL PRIMARY KEY,
  role          TEXT        NOT NULL CHECK (role IN ('student', 'parent', 'teacher')),
  full_name     TEXT        NOT NULL,
  email         TEXT        NOT NULL,
  phone         TEXT,
  password_hash TEXT        NOT NULL,
  register_id   BIGINT      REFERENCES register(id)       ON DELETE RESTRICT,
  staff_id      BIGINT      REFERENCES staff_register(id) ON DELETE RESTRICT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_login_at TIMESTAMPTZ,

  -- A student/parent account must point at a register row; a teacher at staff.
  CONSTRAINT users_link_matches_role CHECK (
    (role IN ('student', 'parent') AND register_id IS NOT NULL AND staff_id IS NULL) OR
    (role = 'teacher'              AND staff_id    IS NOT NULL AND register_id IS NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users (lower(email));

-- One student account and one parent account per enrolled child.
CREATE UNIQUE INDEX IF NOT EXISTS users_register_role_key
  ON users (register_id, role) WHERE register_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_staff_key
  ON users (staff_id) WHERE staff_id IS NOT NULL;

-- --- Sessions -------------------------------------------------------------
-- token_hash holds SHA-256 of the cookie value, never the value itself, so a
-- database leak does not hand over live sessions.
CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT        PRIMARY KEY,
  user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  user_agent TEXT
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx  ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_idx  ON sessions (expires_at);

-- --- Rate limiting --------------------------------------------------------
CREATE TABLE IF NOT EXISTS auth_attempts (
  id         BIGSERIAL PRIMARY KEY,
  bucket     TEXT        NOT NULL,
  succeeded  BOOLEAN     NOT NULL DEFAULT false,
  at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS auth_attempts_bucket_at_idx ON auth_attempts (bucket, at DESC);
`;

export const PORTAL_SQL = `-- ===========================================================================
-- Bright Future Secondary School - student portal data
-- Apply after db/schema.sql:  psql "$DATABASE_URL" -f db/portal-schema.sql
-- Safe to re-run.
-- ===========================================================================

-- --- Subjects and the people who teach them -------------------------------
CREATE TABLE IF NOT EXISTS subjects (
  id         BIGSERIAL PRIMARY KEY,
  name       TEXT NOT NULL,
  -- Drives the tile colour on the dashboard.
  accent     TEXT NOT NULL DEFAULT 'blue'
             CHECK (accent IN ('blue','green','purple','orange','teal','pink','navy')),
  icon       TEXT NOT NULL DEFAULT 'book'
);
CREATE UNIQUE INDEX IF NOT EXISTS subjects_name_key ON subjects (lower(name));

-- --- Timetable ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS timetable (
  id          BIGSERIAL PRIMARY KEY,
  class_level TEXT NOT NULL,
  class_arm   TEXT NOT NULL DEFAULT '',      -- "A" in SS2A; blank means the whole year
  weekday     SMALLINT NOT NULL CHECK (weekday BETWEEN 1 AND 5),   -- 1 = Monday
  starts_at   TIME NOT NULL,
  ends_at     TIME NOT NULL,
  subject_id  BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  teacher     TEXT NOT NULL,
  room        TEXT NOT NULL DEFAULT '',
  CHECK (ends_at > starts_at)
);
CREATE INDEX IF NOT EXISTS timetable_class_day_idx ON timetable (class_level, class_arm, weekday, starts_at);

-- --- Assignments ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS assignments (
  id          BIGSERIAL PRIMARY KEY,
  class_level TEXT NOT NULL,
  class_arm   TEXT NOT NULL DEFAULT '',
  subject_id  BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  brief       TEXT NOT NULL DEFAULT '',
  due_on      DATE NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS assignments_class_due_idx ON assignments (class_level, class_arm, due_on DESC);

-- Per-pupil state. No row means not yet submitted.
CREATE TABLE IF NOT EXISTS assignment_submissions (
  assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
  register_id   BIGINT NOT NULL REFERENCES register(id)    ON DELETE CASCADE,
  submitted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  score         NUMERIC(5,2),
  PRIMARY KEY (assignment_id, register_id)
);

-- --- Results --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subject_results (
  id          BIGSERIAL PRIMARY KEY,
  register_id BIGINT NOT NULL REFERENCES register(id) ON DELETE CASCADE,
  subject_id  BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
  session     TEXT NOT NULL,                 -- e.g. 2024/2025
  term        SMALLINT NOT NULL CHECK (term BETWEEN 1 AND 3),
  score       NUMERIC(5,2) NOT NULL CHECK (score >= 0 AND score <= 100),
  UNIQUE (register_id, subject_id, session, term)
);

-- --- Attendance -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS attendance (
  id          BIGSERIAL PRIMARY KEY,
  register_id BIGINT NOT NULL REFERENCES register(id) ON DELETE CASCADE,
  on_date     DATE NOT NULL,
  state       TEXT NOT NULL CHECK (state IN ('present','absent','late')),
  UNIQUE (register_id, on_date)
);
CREATE INDEX IF NOT EXISTS attendance_register_idx ON attendance (register_id, on_date DESC);

-- --- Announcements --------------------------------------------------------
CREATE TABLE IF NOT EXISTS announcements (
  id           BIGSERIAL PRIMARY KEY,
  title        TEXT NOT NULL,
  body         TEXT NOT NULL,
  published_on DATE NOT NULL DEFAULT current_date,
  audience     TEXT NOT NULL DEFAULT 'all'
               CHECK (audience IN ('all','students','parents','staff'))
);
CREATE INDEX IF NOT EXISTS announcements_published_idx ON announcements (published_on DESC);

-- --- Messages -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
  id           BIGSERIAL PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sender       TEXT NOT NULL,
  subject      TEXT NOT NULL,
  body         TEXT NOT NULL DEFAULT '',
  sent_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS messages_user_idx ON messages (user_id, sent_at DESC);

-- --- Term calendar --------------------------------------------------------
-- One row per term, so the dashboard can show the term name and days remaining
-- instead of hard-coding them.
CREATE TABLE IF NOT EXISTS terms (
  id       BIGSERIAL PRIMARY KEY,
  session  TEXT NOT NULL,
  term     SMALLINT NOT NULL CHECK (term BETWEEN 1 AND 3),
  label    TEXT NOT NULL,
  starts_on DATE NOT NULL,
  ends_on   DATE NOT NULL,
  UNIQUE (session, term),
  CHECK (ends_on > starts_on)
);

-- --- Where a register row came from ---------------------------------------
-- 'import' means it came from the school's spreadsheet; 'signup' means an open
-- sign-up created it. Sign-up stays open until at least one imported row exists,
-- so creating an account does not close the door behind it.
ALTER TABLE register       ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'import';
ALTER TABLE staff_register ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'import';

-- --- Class arm ------------------------------------------------------------
-- SS2A is class_level SS2 plus arm A. Added here rather than in the auth
-- schema so sign-up keeps asking only for the year group.
ALTER TABLE register ADD COLUMN IF NOT EXISTS class_arm TEXT NOT NULL DEFAULT '';
`;

export const DEMO_REGISTER_SQL = `-- Demo register rows, for trying the portal before the real spreadsheet is
-- imported. Do NOT load this into production.
INSERT INTO register (admission_no, surname, other_names, class_level, guardian_email, guardian_phone, status, source) VALUES
  ('BFS/2025/0142', 'Okafor',  'Chidera Ada',   'SS2',  'amaka.okafor@example.com', '+234 802 111 2233', 'active', 'demo'),
  ('BFS/2025/0187', 'Bello',   'Ibrahim Musa',  'JSS2', 'amina.bello@example.com',  '08033445566',       'active', 'demo'),
  ('BFS/2024/0091', 'Adeyemi', 'Tunde Samuel',  'SS3',  NULL,                        '+234 805 777 8899', 'active', 'demo'),
  ('BFS/2019/0007', 'Eze',     'Ngozi Grace',   'SS3',  'ngozi.eze@example.com',     NULL,                'left', 'demo')
ON CONFLICT (upper(replace(admission_no, ' ', ''))) DO NOTHING;

INSERT INTO staff_register (staff_no, surname, other_names, email, status, source) VALUES
  ('BFS/STF/014', 'Ogun',    'Folake',  'folake.ogun@brightfuture.edu.ng', 'active', 'demo'),
  ('BFS/STF/022', 'Ibrahim', 'Samuel',  NULL,                              'active', 'demo')
ON CONFLICT (upper(replace(staff_no, ' ', ''))) DO NOTHING;
`;

export const DEMO_PORTAL_SQL = `-- ===========================================================================
-- Demo portal data. Mirrors the dashboard design so the page can be seen
-- working before real school data is loaded. Do NOT load into production.
-- Safe to re-run.
-- ===========================================================================

INSERT INTO subjects (name, accent, icon) VALUES
  ('Mathematics',      'blue',   'calc'),
  ('English Language', 'purple', 'book'),
  ('Biology',          'green',  'leaf'),
  ('Computer Studies', 'teal',   'laptop'),
  ('Physics',          'orange', 'atom'),
  ('Chemistry',        'pink',   'flask')
ON CONFLICT (lower(name)) DO NOTHING;

INSERT INTO terms (session, term, label, starts_on, ends_on) VALUES
  ('2024/2025', 1, 'First Term',  DATE '2024-09-09', DATE '2024-12-13'),
  ('2024/2025', 2, 'Second Term', current_date - 22, current_date + 68),
  ('2024/2025', 3, 'Third Term',  current_date + 90, current_date + 180)
ON CONFLICT (session, term) DO UPDATE
  SET starts_on = EXCLUDED.starts_on, ends_on = EXCLUDED.ends_on;

-- Daniel James, the pupil shown in the dashboard design.
INSERT INTO register (admission_no, surname, other_names, class_level, class_arm,
                      guardian_email, guardian_phone, status, source)
VALUES ('BFS/2024/0178', 'James', 'Daniel', 'SS2', 'A',
        'mrs.james@example.com', '+234 806 222 3344', 'active', 'demo')
ON CONFLICT (upper(replace(admission_no, ' ', ''))) DO UPDATE
  SET class_arm = EXCLUDED.class_arm, other_names = EXCLUDED.other_names;

-- Give the other demo pupils an arm too.
UPDATE register SET class_arm = 'A' WHERE class_arm = '';

-- --- Timetable for SS2A ---------------------------------------------------
DELETE FROM timetable WHERE class_level = 'SS2' AND class_arm = 'A';
INSERT INTO timetable (class_level, class_arm, weekday, starts_at, ends_at, subject_id, teacher, room)
SELECT 'SS2', 'A', d.weekday, t.starts_at, t.ends_at, s.id, t.teacher, t.room
FROM (VALUES
  ('Mathematics',      TIME '08:00', TIME '09:00', 'Mr. Okafor',   'Room 12'),
  ('English Language', TIME '09:00', TIME '10:00', 'Mrs. Bello',   'Room 8'),
  ('Biology',          TIME '10:30', TIME '11:30', 'Mr. Okoro',    'Lab 1'),
  ('Computer Studies', TIME '12:00', TIME '13:00', 'Mrs. Ibrahim', 'ICT 2'),
  ('Physics',          TIME '14:00', TIME '15:00', 'Mr. Adeyemi',  'Lab 2')
) AS t(subject, starts_at, ends_at, teacher, room)
JOIN subjects s ON s.name = t.subject
CROSS JOIN (VALUES (1),(2),(3),(4),(5)) AS d(weekday);

-- --- Assignments ----------------------------------------------------------
DELETE FROM assignments WHERE class_level = 'SS2' AND class_arm = 'A';
INSERT INTO assignments (class_level, class_arm, subject_id, title, brief, due_on)
SELECT 'SS2', 'A', s.id, a.title, a.brief, a.due_on
FROM (VALUES
  ('Mathematics',      'Mathematics Homework', 'Solve exercises 1 - 10 in the textbook.',                 current_date + 3),
  ('English Language', 'English Essay',        'Write a 500-word essay on "The Importance of Education".', current_date + 4),
  ('Biology',          'Biology Project',      'Research on cell division and present a report.',          current_date + 6),
  ('Computer Studies', 'ICT Practical',        'Create a simple website using HTML & CSS.',                current_date + 8)
) AS a(subject, title, brief, due_on)
JOIN subjects s ON s.name = a.subject;

-- Daniel has handed in the maths homework only.
INSERT INTO assignment_submissions (assignment_id, register_id)
SELECT a.id, r.id
FROM assignments a
JOIN register r ON upper(replace(r.admission_no,' ','')) = 'BFS/2024/0178'
WHERE a.title = 'Mathematics Homework'
ON CONFLICT DO NOTHING;

-- --- Results --------------------------------------------------------------
INSERT INTO subject_results (register_id, subject_id, session, term, score)
SELECT r.id, s.id, '2024/2025', 2, v.score
FROM (VALUES
  ('Mathematics', 88), ('English Language', 80), ('Biology', 85),
  ('Computer Studies', 78), ('Physics', 83)
) AS v(subject, score)
JOIN subjects s ON s.name = v.subject
JOIN register r ON upper(replace(r.admission_no,' ','')) = 'BFS/2024/0178'
ON CONFLICT (register_id, subject_id, session, term) DO UPDATE SET score = EXCLUDED.score;

-- --- Attendance: 46 present, 2 absent, 1 late -----------------------------
DELETE FROM attendance
 WHERE register_id = (SELECT id FROM register WHERE upper(replace(admission_no,' ','')) = 'BFS/2024/0178');
INSERT INTO attendance (register_id, on_date, state)
SELECT r.id,
       d.day,
       CASE WHEN row_number() OVER (ORDER BY d.day) IN (12, 27) THEN 'absent'
            WHEN row_number() OVER (ORDER BY d.day) = 34        THEN 'late'
            ELSE 'present' END
FROM register r
CROSS JOIN LATERAL (
  -- The last 49 weekdays.
  SELECT day::date AS day
    FROM generate_series(current_date - 90, current_date, interval '1 day') AS day
   WHERE extract(isodow FROM day) BETWEEN 1 AND 5
   ORDER BY day DESC
   LIMIT 49
) AS d
WHERE upper(replace(r.admission_no,' ','')) = 'BFS/2024/0178';

-- --- Announcements --------------------------------------------------------
DELETE FROM announcements;
INSERT INTO announcements (title, body, published_on, audience) VALUES
  ('Inter-house Sports Competition',
   'The annual inter-house sports competition will hold next month. Houses should begin practice with their sports prefects.',
   current_date - 4, 'all'),
  ('ICT Lab Upgrade',
   'The ICT lab has been upgraded with new computers and modern software for coding and CBT practice.',
   current_date - 7, 'all'),
  ('School Fees Reminder',
   'Kindly pay your term fees before the end of the month. Speak to the bursary about instalment plans.',
   current_date - 10, 'all'),
  ('Second Term Examinations',
   'End of term examinations begin in the final two weeks of term. Timetables will be posted on the notice board.',
   current_date - 14, 'students');

-- --- Messages: three unread, matching the badge in the design -------------
DELETE FROM messages WHERE user_id IN (
  SELECT u.id FROM users u JOIN register r ON r.id = u.register_id
   WHERE upper(replace(r.admission_no,' ','')) = 'BFS/2024/0178');
INSERT INTO messages (user_id, sender, subject, body, sent_at, read_at)
SELECT u.id, v.sender, v.subject, v.body, now() - (v.hours || ' hours')::interval, NULL
FROM users u
JOIN register r ON r.id = u.register_id
CROSS JOIN (VALUES
  ('Mr. Okafor',   'Well done on your last test', 'Your work on quadratic equations has improved a great deal. Keep it up.', 5),
  ('Mrs. Bello',   'Essay title confirmed',       'Please use the title exactly as given. Hand-written submissions are fine.', 26),
  ('School Office','Fees reminder',               'Kindly pay your term fees before the end of the month.', 50)
) AS v(sender, subject, body, hours)
WHERE upper(replace(r.admission_no,' ','')) = 'BFS/2024/0178';
`;
