/* Embeds the SQL files into a JS module.
 *
 * The migrate endpoint runs on Vercel, where only files the bundler can trace
 * are shipped with the function. A readFile of db/*.sql is not traced, so the
 * SQL is compiled into api/_lib/schema.js, which an import does trace.
 *
 * db/*.sql stays the source of truth. Run this after changing one:
 *   node scripts/build-schema.mjs
 * npm run check fails if the generated file has drifted.
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

export const SOURCES = {
  SCHEMA_SQL: "schema.sql",
  PORTAL_SQL: "portal-schema.sql",
  DEMO_REGISTER_SQL: "demo-register.sql",
  DEMO_PORTAL_SQL: "demo-portal.sql",
};

export async function render() {
  const parts = ["/* GENERATED by scripts/build-schema.mjs. Edit db/*.sql, not this file. */\n"];
  for (const [name, file] of Object.entries(SOURCES)) {
    const sql = await readFile(join(ROOT, "db", file), "utf8");
    // A template literal keeps the SQL readable; only backticks and ${ need escaping.
    const escaped = sql.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    parts.push(`\nexport const ${name} = \`${escaped}\`;\n`);
  }
  return parts.join("");
}

// Only write when run directly, so check-deploy can import render() to compare.
if (process.argv[1] && process.argv[1].endsWith("build-schema.mjs")) {
  const out = join(ROOT, "api", "_lib", "schema.js");
  await writeFile(out, await render(), "utf8");
  console.log("wrote api/_lib/schema.js from db/*.sql");
}
